In [2]:
import pandas as pd
s=pd.Series([1,2,3,4,5])

In [7]:
data_dic={'id':[1,2,3,4],'salary':[244,255,267,278],'department':['abc','def','ghi','jkl']}
df2=pd.DataFrame(data_dic,columns=['id','salary','department'])
df2

   id  salary department
0   1     244        abc
1   2     255        def
2   3     267        ghi
3   4     278        jkl

In [9]:
data=[[1,244,'abc'],[2,255,'def'],[3,267,'ghi']]
df=pd.DataFrame(data,columns=['id','salary','department'])
(df)
index=['row1','row2','row3']
df.index=index
df

      id  salary department
row1   1     244        abc
row2   2     255        def
row3   3     267        ghi

In [10]:
df['department'].dtype

dtype('O')

In [11]:
df['department']=df['department'].astype('category')
df['department'].dtype

CategoricalDtype(categories=['abc', 'def', 'ghi'], ordered=False, categories_dtype=object)